# Based on https://github.com/retep998/winapi-rs/blob/0.3.3/appveyor.yml

environment:
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu
  - TARGET: 1.13.0-x86_64-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
build_script:
  - cargo build
test_script:
- cargo test
